version: "3"

services:
  
  app:
    ports:
      - 22:22/tcp
      - 80:80/tcp
      - 443:443/tcp
    env_file:
      - ./.env
    tty: true
    stdin_open: true
    hostname: dev.feef.org
    image: davask/local-lamp
    restart: always
    networks:
      - dwlhost
    volumes:
      - /c/Users/david/Documents/repo/p-feeforgwww:/home/davask/files
      - ./volumes/etc/apache2/sites-available:/etc/apache2/sites-available
      - ./volumes/etc/apache2/ssl:/etc/apache2/ssl
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306/tcp
    environment:
      MARIADB_ROOT_PASSWORD: davask
    volumes:
      - ./volumes/var/lib/mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
    dwlhost:
        external: true

# docker network create -d bridge --subnet 192.168.0.0/24 --gateway 192.168.0.1 dwlhost
# docker-compose up -d
# export COMPOSE_HTTP_TIMEOUT=600;
# docker exec -ti proxy_reverse_1 sh -c 'bash /dwl/init.sh'
# docker-compose -f /home/dwl/docker-images/app/d-wordpress/docker-compose.yml up -d
# docker exec -ti  sh -c 'mysqldump -u root -p  > /docker-entrypoint-initdb.d/-171218-170818.sql'